### ISSUE TITLE
Doesn't work with PostgresQL

### ISSUE THREAD

**Issue by choffstein** [theAlmanac/crewait#2]
Quick fix:

For postgres adapter in next_insert_id:

return ActiveRecord::Base.connection.execute("SELECT nextval('#{self.table_name}_id_seq')")[0]["nextval"].to_i

**Comment by michaelglass** [comment]
nice find.  I don't have postgresql running locally, if you fork it we'll push the changes.

(thanks)

**Comment by choffstein** [comment]
Forked, code added, tested locally -- feel free to check it out.

**Comment by skoder** [comment]
Note that this behaviour depends of postgres gem. 
For example, with postgres gem connection.execute will return array instead of hash.
