### ISSUE TITLE
Cannot Handle Namespaced Models

### ISSUE THREAD

**Issue by alexkalish** [theAlmanac/crewait#4]
Hi!  This gem is exactly what I've been looking for, but it doesn't seem to handle namespaced models, i.e. 'Building::House'.

Looking at the source, self.for(model, hash) gets the table name to key into hash_of_hashes and hash_of_next_inserts, which makes sense.  But then in self.go!, there is a call  to eval(key.classify), which tries to turn the table name back into the class constant.  Unless I'm missing something, this can never work for namescaped modules.  Building::House will become 'building_house' and then 'BuildingHouse', which cannot be evaluated.  Is there a reason to go back to the class constant from the table name?

Do please let me know if I'm missing something.  I could certainly fork and change if I've diagnosed the problem correctly.

Thanks so much!

**Comment by theAlmanac** [comment]
Hey Alex: thanks for identifying this problem! Go ahead and fork and change – I imagine you just use the model object itself as the key in @@hash_of_next_inserts and @@hash_of_hashes, and then just call #table_name whenever it's need right? Sounds like a fine solution to me!
