### ISSUE TITLE
problem in sqlite3

### ISSUE THREAD

**Issue by yangjiandong** [theAlmanac/crewait#5]
jruby1.6rc1,ror3.0.1,jdk16_23,jdbcslqite3
code:
         Hz.crewait(
           :hz => record['hz'],
           :py => record['py'],
           :wb => record['wb']
         )
error:
undefined method `current_database' for #ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x18be647

**Comment by yangjiandong** [comment]
use mysql,error:
undefined method `fetch_hash' for [{"auto_increment"=>nil}]:Array

**Comment by yangjiandong** [comment]
?

**Comment by skwp** [comment]
I am also seeing this problem.
